Add bookings
Vkurse/java-shareit pull request #2
Opened 2023-06-09 08:04 UTC by Vkurse

2023-06-10 10:23 UTC, Fleaman777 requested changes

2023-06-10 10:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                              @RequestParam(name = "approved") Boolean approved) {
можно не указывать значение для name параметра, если оно совпадает с названием аргумента метода
меньше кода, меньше отвлекающих вещей

2023-06-10 10:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    }
можно явно не указывать конструктор и аннотацию @Autowire над ним, что бы внедрить компоненты. 
Достаточно повесить аннотацию @RequiredArgыConstructor над классом, 

так будет меньше бойлер плейт кода

2023-06-10 10:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    public BookingInfoDto addBooking(Long userId, BookingDto bookingDto) {
метод изменяет состояние БД, правильней было бы его выполнять в транзакции, 

относится ко всем аналогичным местам

2023-06-10 10:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +                bookingList = repository.findAllByBookerIdAndEndIsBefore(user.getId(), LocalDateTime.now(), sort);
LocalDateTime.now() можно было бы вынести в локальную перменную, что бы не дублировать получение текущей даты

2023-06-10 10:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        return bookingList.isEmpty() ? Collections.emptyList() : bookingList.stream()
в целом, этот тернарный оператор не обезателен, 
т.е. если пройтись стримом по пустому списку, стрим вернет пустой список

2023-06-10 10:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +                bookingList = repository.findAllByItem_Owner_IdAndStartIsBeforeAndEndIsAfter(user.getId(), LocalDateTime.now(), LocalDateTime.now(), sort);
аналагично с LocalDateTime.now()

2023-06-10 10:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private final ItemJpaServiceImpl itemService;
в качестве типа нужно использовать не конкретную реализацию интерфейса, а сам интерфейс, что уменьшает связанность кода 

буква D в аббревиатуре SOLID - принципы в программировании

2023-06-10 10:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemJpaServiceImpl.java
> +        if (!bookingList.isEmpty()) {
как упомянул ранее, если список использовать в стриме, не обязательно его перед этим проверять на пустоту, 

меньше условий, чище код

2023-06-10 10:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemJpaServiceImpl.java
> +    private Boolean isAlreadyBook(Long userId, Long itemId) {
isAlreadyBooked небольшая опечатка

2023-06-10 10:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/service/UserJpaServiceImpl.java
> +public class UserJpaServiceImpl implements UserService {
я бы убрал из названия JPA поскольку это немного сбивает, 
обычно все, что в названии содержит JPA связано с обращением у БД,
в данном случае у тебя сервис, который обращается к БД через репозиторий класс

2023-06-10 10:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/service/UserJpaServiceImpl.java
> +    private User userPatch(User updatedUser, UserDto user) {
под patch может скрываться много вещей,
хорошо было бы уточнить, что именно делает этот метод

2023-06-13 12:49 UTC, Vkurse commented
Привет! Большое спасибо за ревью! Немного не разобралась с стримами и переменной с LocalDateTame.now()... Прошу пока принять так, как только у меня появиться свободное время обязательно займусь этой темой.

2023-06-14 11:17 UTC, Fleaman777 approved these changes

2023-06-14 12:43 UTC, merged