Add item requests
Vkurse/java-shareit pull request #3
Opened 2023-06-25 14:52 UTC by Vkurse

2023-06-26 19:00 UTC, Fleaman777 requested changes

2023-06-26 19:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                           @RequestParam(name = "from", required = false, defaultValue = "0") Integer from,
можно не указывать значение для name параметра, если оно совпадает с названием аргумента метода
меньше кода, меньше отвлекающих вещей

2023-06-26 19:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        if (from < 0 || size < 0) {
в контроллере не должно быть валидаций, не считая аннотаций, вся логика в слое сервис

2023-06-26 19:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            return ItemMapper.toDto(repository.save(newItem));
метод изменяет состояние БД, правильней было бы его выполнять в транзакции,

2023-06-26 19:00 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", 10)
X-Sharer-User-Id в тестах так же можно было бы вынести в константу

2023-06-26 19:00 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    void updateBookingStatus() throws Exception {
название тест метода должно отличаться от названия основного метода, что бы, например, такой метод было проще искать по всему коду, не отвлекаясь на тестовые

хорошо бы в названии указывать прикаких условиях проводится ткст и какой ожидается результат,

аналогично в других местах

2023-06-26 19:00 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceTest.java
> +        when(bookingRepository.findAllByItem_Owner_IdOrderByStartDesc(anyLong(), any())).thenReturn(List.of(booking));
по правильному, тест должен проверять только какой-то один метод,  в таком случае их будет проще поддерживать и понимать, 
можно сказать, в тесте будет применятся принцип разделения ответсвенности 

к том же, когда тест отвечает только за проверку какого-то одного функционала, проще будет придумать ему правильное название из которого будет понятно, что именно делает тест

2023-06-26 19:00 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceImplTest.java
> +}
посмотри какие общие вещи можно вынести в отдельные вспомогательные методы или в метод setUp. 
это поможет уменьшить дублирование, а соответственно повысить читаемость кода

этот комментарий в разной степени относится почти ко всем тестовым классам

2023-06-26 19:00 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/user/controller/UserControllerTest.java
> +package ru.practicum.shareit.user.controller;
хорошая, правильная структура тестов, каждый тестовый лкасс лежит в своем подпакете

2023-06-26 19:00 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/user/service/UserServiceImplTest.java
> +}
необходимо еще написать тесты для репозиторий слоев,
в задании написано, покрыть тестами кастомные методы, по сути, все методы которые находятся в ....Repository являются кастомными,
некастомные методы, это методы в интерфейсе JpaRepository (save, find..) их соответственно тестировать не нужно

2023-06-28 13:48 UTC, Vkurse commented
Привет! Спасибо за столь подробное ревью, надеюсь что всё правильно поняла и исправила!

2023-06-29 13:47 UTC, Fleaman777 approved these changes

2023-06-29 16:01 UTC, merged